import = ["~/.config/alacritty/themes/themes/everblush.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 10

startup_mode = "Maximized"
decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
size = 12

[cursor]
style.shape = "Block"
style.blinking = "On"
blink_interval = 300
blink_timeout = 0

